language: scala
sudo: false

os:
  - linux
dist: xenial

scala:
  - 2.12.11
  - 2.13.2

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - echo -e 'user = u\npassword = p' > local.properties

install:
  - wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
  - tar xvzf aerospike-server.tgz
  - cp -f .travis/aerospike.conf ./aerospike-server/share/etc
  - cd aerospike-server
  - sed -i -e 's/\${me}/"root"/' share/libexec/aerospike-start
  - sed -i -e 's/set_shmall$/#set_shmall/' share/libexec/aerospike-start
  - sed -i -e 's/set_shmmax$/#set_shmmax/' share/libexec/aerospike-start
  - mkdir instance1
  - mkdir instance2
  - ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
  - ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
  - cd instance1
  - sudo ./bin/aerospike start
  - ../../.travis/wait-for-node.sh var/log/aerospike.log
  - cd ..
  - cd instance2
  - sudo ./bin/aerospike start
  - ../../.travis/wait-for-node.sh var/log/aerospike.log
  - cd ../..

script:
  - sbt ++$TRAVIS_SCALA_VERSION test